# ==============================================================
# account-service – Spring Boot  |  Port 8083
# Depends on: postgres, rabbitmq, auth-service, core-banking-mock
# ==============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: saving-banking
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: localhost:5001/account-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
              value: account_schema
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            failureThreshold: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: saving-banking
  labels:
    app: account-service
spec:
  selector:
    app: account-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
