# LOCAL DEVELOPMENT PROFILE — activate with SPRING_PROFILES_ACTIVE=local

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saving_banking
    username: postgres
    password: postgres

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

cbs:
  url: http://localhost:8099

logging:
  level:
    com.saving.transaction: DEBUG
